menu:
  Home: /
  About: /about
  Archive: /archives
  RSS: /atom.xml

widgets:
- search
- about_me
- calendar
- category
- duoshuo_recent_comments
- tagcloud
- recent_posts
- links

highlightjs: monokai_sublime

excerpt_link: 阅读...
archive_yearly: false #按年存档


twitter_id:
facebook_id:
github_id: haskio

addthis:
 # enable: false
  pubid:
  facebook: false
  twitter: false
  google: false
  pinterest: false

fancybox: true

google_analytics:
rss: /atom.xml

links:
- name: Life Blog
  link: http://blog.wileam.com


duoshuo: fea-shine

about_me:
  title: ABOUT ME
  avatar: /uploads/avatar.jpg
  texts:
  - <a href="/about" target="_BLANK">非想 </a>
  - 无聊了，就写点东西。记记时间，录录岁月
  - <br>

